### PR TITLE
fix: cookies functionality, hyperlinks and shown appropriate content in footer

### LINKED ISSUE #1070: Bug: Problem in Footer after Logging In
### Description

According to Code in Footer.jsx, after successful login their should be "EVENTS" instead of "Join Us" But this is not happening.

Here I have logged in :-
Screenshot (40)

I don't think I can solve this because it is related to authToken I guess but I feel that this needs to be solved.

### Screenshots

_No response_

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

### PR DESCRIPTION
**Pull request by YuvarajSingh-0**
closes #1070 

### 👷🏻 Changes made  
Corrected cookie names all around code and fixed backend code that fixes this issue.

### 📸 Screenshots 
Before Logging in 👇
image

After logging in 👇
Screenshot 2023-09-25 161216

### CODE REVIEW

**Comment by YuvarajSingh-0** [comment]
@tamalCodes Is this good?

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Hi @YuvarajSingh-0 , i don't think you need to change any backend code OR the cookie name. The `isLoggedIn` cookie is being set and cleared by the backend itself - there's a logout issue because of the `domain` property maybe which I am working on actively.

However, with context to this issue, the `isLoggedIn` property is accessible in the code, look at the Navbar for example. Please use that cookie itself without further modifying any server-side code OR cookie name for the same.

Waiting for the changes in the PR !

**Comment by YuvarajSingh-0** [comment]
@tamalCodes You mentioned the backend  clears the isLoggedIn cookie but it doesn't which also raises issues with sign in and signup button visibility after logging out, but as you mentioned you are working on it, I am not going to modify anything in backend.

Let me modify the code to create new PR

File: src/components/Footer/Footer.jsx [hunk 1]
```diff
@@ -38,7 +38,12 @@ const Footer = () => {
...
 
   useEffect(() => {
-    if (Cookies.get("token")) setLogged(true);
+    if (
+      Cookies.get("Token") ||
+      Cookies.get("OAuthLoginInitiated") ||
+      Cookies.get("isLoggedIn")
+    )
+      setLogged(true);
   }, []);
```
Comment (tamalCodes) [inline src/components/Footer/Footer.jsx:47]: I think there is no need to maintain a state for the logged-in part. Wherever needed we can simply directly check the `Cookies.get("isLoggedIn")` property.

File: src/components/Footer/Footer.jsx [hunk 2]
```diff
@@ -56,7 +61,7 @@ const Footer = () => {
   const handleReportSubmit = async (e) => {
     e.preventDefault();
 
-    if (!Cookies.get("token")) {
+    if (!Cookies.get("Token")) {
```
Comment (tamalCodes) [inline src/components/Footer/Footer.jsx:64]:
```suggestion
    if (!Cookies.get("isLoggedIn")) {
```

Please change the `Token` cookie

File: src/pages/Donate/Donate.jsx [hunk 3]
```diff
@@ -16,7 +16,7 @@ const Donate = () => {
 
   const [clubData, setClubData] = useState([]);
   const [loading, setLoading] = useState(false);
-  const [isLoggedIn] = useState(Cookies.get("token"));
+  const [isLoggedIn] = useState(Cookies.get("Token"));
```
Comment (tamalCodes) [inline src/pages/Donate/Donate.jsx:19]: Again, I think it would be better to remove the states all through out.

**Review by tamalCodes — CHANGES_REQUESTED** [review]

File: src/components/Banners/HomeBanner.jsx [hunk 4]
```diff
@@ -40,7 +40,7 @@ const HomeBanner = () => {
               </div>
 
               <div className="banner_signup_btndiv">
-                {Cookies.get("token") || Cookies.get("club") ? (
+                {Cookies.get("Token") || Cookies.get("club") ? (
```
Comment (tamalCodes) [inline src/components/Banners/HomeBanner.jsx:43]:
```suggestion
                {Cookies.get("isLoggedIn") ? (
```

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Please make these minor changes.

File: src/components/Footer/Footer.jsx (hunk 1 above)
Comment (YuvarajSingh-0) [reply src/components/Footer/Footer.jsx:47]: But we are conditionally rendering the components in the footer. I think we need it. But if you say so I will remove it. 
Awaiting for your reply

File: src/components/Footer/Footer.jsx (hunk 2 above)
Comment (YuvarajSingh-0) [reply src/components/Footer/Footer.jsx:64]: what do you mean by 'change'?

File: src/components/Footer/Footer.jsx (hunk 1 above)
Comment (tamalCodes) [reply src/components/Footer/Footer.jsx:47]: The place where we are conditionally rendering it, can't we just use the cookies directly ? 

```jsx

{Cookies.get("isLoggedIn") ? <>show this</> :  <>show this</> }
```

Comment (tamalCodes) [reply src/components/Footer/Footer.jsx:47]: Hi @YuvarajSingh-0 , can you please do this change so that we can merge this PR ?

Comment (YuvarajSingh-0) [reply src/components/Footer/Footer.jsx:47]: Right.... Will complete it by the end of the day

Comment (YuvarajSingh-0) [reply src/components/Footer/Footer.jsx]: @tamalCodes completed everything you told. 
Please Review it.

File: src/pages/Donate/Donate.jsx (hunk 3 above)
Comment (YuvarajSingh-0) [reply src/pages/Donate/Donate.jsx]: Removed the states and implemented with Cookies.

File: src/components/Banners/HomeBanner.jsx
Comment (tamalCodes) [inline src/components/Banners/HomeBanner.jsx:1]: This file seems to have some conflicts, please fix them.

**Review by tamalCodes — CHANGES_REQUESTED** [review]

File: src/components/Banners/HomeBanner.jsx
Comment (YuvarajSingh-0) [reply src/components/Banners/HomeBanner.jsx:1]: Please check it now.

Comment (tamalCodes) [inline src/components/Banners/HomeBanner.jsx:1]: It looks like you have resolved the conflicts in the wrong manner. You overwrote the incoming changes (the changes that I made) with the changes of the current branch (the changes that you had previously).

That is a reason why some UI has also changed. Take a look at this screenshot below.
The left image is the changes that are made by you. The right one is what is currently deployed.

image


Please fix this.

**Review by tamalCodes — CHANGES_REQUESTED** [review]

File: src/components/Banners/HomeBanner.jsx
Comment (YuvarajSingh-0) [reply src/components/Banners/HomeBanner.jsx:1]: So, you want the left image to look like the right one.... Right?

Comment (tamalCodes) [reply src/components/Banners/HomeBanner.jsx:1]: Correct. You can check the current code that we have for more reference.

Comment (YuvarajSingh-0) [reply src/components/Banners/HomeBanner.jsx:1]: What should I replace in place of 'usertype' cookie? (in line number 28 in [HomeBanner.jsx](https://github.com/MilanCommunity/Milan/blob/main/src/components/Banners/HomeBanner.jsx)

Comment (tamalCodes) [reply src/components/Banners/HomeBanner.jsx:1]: I think starting from [here](https://github.com/MilanCommunity/Milan/blob/a5be3e675151b2920168a2aec1e1d0a0b8939db7/src/components/Banners/HomeBanner.jsx#L27) it would be the best to keep the changes as it is. 

I previously updated the code for the home banner about what to show in the buttons on instances where the user is not logged in, the club is logged in OR the user is logged in. So I think we can maybe ignore the changes for the `HomeBanner.jsx` file.

Comment (YuvarajSingh-0) [reply src/components/Banners/HomeBanner.jsx:1]: Yes, It's Working fine, I've checked it now.

There was also an issue with login trigger while logging in i.e., the login functionality is not hitting the correct backend url for login, I fixed it in ApiEndpoints.js file.  And also upon clicking the profile icon after logging in, due to [this](https://github.com/MilanCommunity/Milan/blob/a5be3e675151b2920168a2aec1e1d0a0b8939db7/src/components/Navbar/Navbar.jsx#L22) line the redirecting url does not exist due to no usertype cookie. But I think that part of code depends on backend, like setting cookie with name 'usertype' and all.

Apart from these, the footer section is good to merge. But one thing, While logging out, Both cookies 'isLoggedIn' and 'Token' should be deleted, failing either one may result in inconsistent results while conditional rendering. Because footer only checks 'isLoggedIn' cookie, so even if there is no 'Token' cookie but there is `isLoggedIn` cookie, it still considers it as logged in.

File: src/assets/data/ApiEndpoints.js
Comment (tamalCodes) [inline src/assets/data/ApiEndpoints.js:1]: Please revert the change. Pull the code from the backend once more.
We have made several changes and the correct URL is `/auth/signin`

**Review by tamalCodes — CHANGES_REQUESTED** [review]

File: src/components/Banners/HomeBanner.jsx
Comment (tamalCodes) [reply src/components/Banners/HomeBanner.jsx:1]: The Login and the `usertype` works fine when normally logging in. Google authentication won't work just yet - so please stay tuned. You can learn more about that in [this issue](https://github.com/MilanCommunity/Milan/issues/1091).

The `token` is an HTTP-only cookie - so you won't be able to access the cookie from the front end. So checking for the `Token` cookie makes no sense. Currently, we might have some glitch in the backend where the logout function fails to clear the cookies in production - but it should work properly in the local.

image

**Review by tamalCodes — APPROVED** [review]
# Amazing work 🎉
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/MilanCommunity/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Comment by YuvarajSingh-0** [comment]
It's been great contributing this project, I apologise for the delay.
